#!/usr/bin/env python3
"""The same ladder fitted two ways, differing only in how E is treated.

    python3 lm_scaling/scaling_fit_variants.py                    # the committed harvest
    python3 lm_scaling/scaling_fit_variants.py --form chinchilla  # the other form

    isolated   every arm fitted alone, its own E          6 free E
    pinned     E taken from Ajroldi et al. (arXiv:2608.28308)  0 free E

ITS TABLES ARE NOT SHIPPED. The paper reports these two fits with the ladder's
largest cell HELD OUT -- `scaling_holdout.py`, which reuses the fits and the
table writer here -- because an in-sample residual says how well a form
describes the ladder and not whether it predicts a cell it has not seen. This
CLI is the in-sample counterpart, kept because the holdout quotes it as a
control and because a reader may want it; `tex/` carries the holdout tables
only.

TWO TREATMENTS OF E, and they bracket the question. E is not identifiable over
this ladder's lever, so the honest thing is to show what the data says when
every arm is free to choose its own (isolated) and what it says when the
asymptote is taken from a fit with fifty times the lever (pinned). Earlier
versions also carried `shared`, `shared_beta` and `pinned_beta`; they were
never in the paper and are gone, because five variants of one comparison
invites a reader to pick the flattering one.

Everything except E is per arm in all three, so the family is nested and the
only thing that changes between tables is what the fit is allowed to believe
about the irreducible loss. Writes three LaTeX tables with bootstrap intervals.
"""
import argparse
import math
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
for p in (str(_HERE), str(_HERE.parent)):
    if p not in sys.path:
        sys.path.insert(0, p)

import scaling_fit as SF  # noqa: E402

ORDER = ["attn", "attn-qknorm", "kda-sig-lowrank", "ckda-shipped-lowrank",
         "kda-sig-hybrid-lowrank", "ckda-shipped-hybrid-lowrank"]


def sci(v):
    r"""LaTeX scientific notation: 26500 -> 2.65\times10^{4}.

    "{:.3g}" gives 2.65e+04, which math mode sets literally as "2.65e+04".
    A and B run to 10^5 and are the only columns that need it.
    """
    if not v or math.isnan(v):
        return "0"
    e = int(math.floor(math.log10(abs(v))))
    return rf"{v / 10 ** e:.2f}\times10^{{{e}}}"


def sub(val, ci, fmt="{:.3f}"):
    """A value with its bootstrap interval as a subscript.

    `fmt` is a format string or a callable taking the value.
    """
    f = fmt if callable(fmt) else fmt.format
    if val is None or (isinstance(val, float) and math.isnan(val)):
        return "--"
    if ci is None:
        return f"${f(val)}$"
    lo, hi = ci
    if math.isnan(lo):
        return f"${f(val)}$"
    return f"${f(val)}_{{[{f(lo)},\\,{f(hi)}]}}$"


def get(point, name, arm):
    v = point[name]
    return v[arm] if isinstance(v, dict) else v


def getci(ci, name, arm):
    if name not in ci:
        return None
    v = ci[name]
    return v.get(arm) if isinstance(v, dict) and arm in v else (
        v if not isinstance(v, dict) else None)


def table(kind, point, ci, reps, n_rows, arms, form, caption, label):
    """One LaTeX table: a row per arm, bootstrap interval under every number."""
    iso = kind == "isolated"
    # E is per arm only in the isolated fit. In the other two it is one number
    # for the whole table, so it belongs in the caption rather than repeated
    # down a column.
    # A AND B BELONG IN THE TABLE. They are fitted per arm in every one of
    # these fits, and leaving them out hid the prefactors -- the part of the
    # law that says how the arms differ at fixed exponent -- behind a column
    # list that only showed what varied most visibly.
    # A COLUMN PER PARAMETER THAT ACTUALLY VARIES BETWEEN ARMS. A shared value
    # printed six times reads as six measurements of the same thing; it goes
    # in the caption instead, as E already does. The isolated fit keys `point`
    # by arm, and every parameter varies there by construction.
    names = ["A", "alpha", "B", "beta"] + (["k"] if form == "skaling" else [])
    cols = (["E"] + names if iso
            else [n for n in names if isinstance(point.get(n), dict)])
    head = {"E": "$E$", "A": "$A$", "alpha": r"$\alpha$", "B": "$B$",
            "beta": r"$\beta$", "k": "$k$"}
    # A and B run to 10^4-10^5 and carry wide intervals; three significant
    # figures in scientific form keeps the column readable without pretending
    # to a precision the bootstrap does not support.
    FMT = {"A": sci, "B": sci, "E": "{:.4f}"}
    out = [
        "% Generated by lm_scaling/scaling_fit_variants.py -- regenerate, do not edit.",
        f"%   {n_rows} annealed endpoints, {len(arms)} arms, "
        f"{reps} bootstrap replicates.",
        r"\begin{table}[t]", r"  \centering", r"  \small",
        f"  \\caption{{{caption}}}", f"  \\label{{{label}}}",
        # A and B carry scientific-notation intervals, which makes these wider
        # than the text block; scale the tabular to the line rather than let it
        # overflow into the margin. Needs graphicx.
        r"  \resizebox{\linewidth}{!}{%",
        r"  \begin{tabular}{l" + "r" * (len(cols) + 1) + "}", r"    \toprule",
        "    Arm & " + " & ".join(head[c] for c in cols) + r" & RMSE \\",
        r"    \midrule",
    ]
    for a in arms:
        p = point[a] if iso else point
        c = ci[a] if iso and a in ci else ci
        cells = []
        for name in cols:
            f = FMT.get(name, "{:.3f}")
            if iso:
                cells.append(sub(p[name] if not isinstance(p[name], dict)
                                 else p[name][a],
                                 (ci[name][a] if name in ci else None), f))
            else:
                cells.append(sub(get(p, name, a), getci(c, name, a), f))
        cells.append(f"${p['rmse_by_arm'].get(a, float('nan')):.5f}$")
        out.append(f"    {SF.LABEL.get(a, a)} & " + " & ".join(cells) + r" \\")
    out += [r"    \bottomrule", r"  \end{tabular}%", r"  }",
            r"\end{table}", ""]
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    # The committed ladder harvest by default, like `scaling_fit.py`, so the
    # ten fit variants regenerate from a fresh clone with no arguments.
    ap.add_argument("--data", type=Path,
                    default=_HERE / "harvest" / "megatron_ladder.tsv")
    ap.add_argument("--form", default="skaling", choices=["skaling", "chinchilla"])
    ap.add_argument("--reps", type=int, default=200)
    ap.add_argument("--starts", type=int, default=600)
    ap.add_argument("--boot-starts", type=int, default=6)
    ap.add_argument("--out", type=Path, default=_HERE / "tex")
    a = ap.parse_args(argv)

    rows = SF.load(a.data)
    arms = [x for x in ORDER if any(r["arm"] == x for r in rows)]
    # Drop arms we do not report. They would otherwise reach fit_shared_E,
    # which indexes rows into `arms` and raises on the first one missing.
    dropped = sorted({r["arm"] for r in rows} - set(arms))
    if dropped:
        print(f"  not reported, dropped: {', '.join(dropped)}", flush=True)
    rows = [r for r in rows if r["arm"] in arms]
    n = len(rows)
    Eref = SF.PAPER[a.form]["E"]
    print(f"{n} rows, {len(arms)} arms, form {a.form}, E_ref {Eref}", flush=True)

    specs = [
        ("isolated", dict(isolated=True),
         "Each architecture fitted in isolation: its own irreducible loss "
         "$E$, its own exponents, its own chained-cell offset. $E$ is not "
         "identifiable over one arm's lever in $N$ and $D$, and the scatter "
         "in the $E$ column is the evidence for that -- every arm was trained "
         "on the same corpus with the same tokenizer and held-out split, so a "
         "spread here is slack in the fit, not a property of the mixer.",
         "tab:scaling-isolated"),
        ("pinned", dict(per_arm="all", E_fixed=Eref),
         f"$E$ pinned to ${Eref:.4f}$, the value of \\citet{{ajroldi2026scaling}}, "
         "fitted on the same corpus and held-out split over a ladder reaching "
         "1.7B parameters and 300BT -- a far longer lever in $D$ than ours. "
         "With the asymptote taken from that fit, the exponents here are "
         "determined by our data rather than by slack in $E$.",
         "tab:scaling-pinnedE"),
    ]
    summary = []
    for kind, kw, caption, label in specs:
        print(f"  fitting {kind} ...", flush=True)
        point, ci, got = SF.bootstrap_arms(rows, arms, a.form, reps=a.reps,
                                           starts=a.boot_starts,
                                           point_starts=a.starts, **kw)
        if kind == "isolated":
            npar = sum(p["n_params"] for p in point.values())
            rss = sum((p["rmse"] ** 2) * sum(1 for r in rows if r["arm"] == arm)
                      for arm, p in point.items())
        else:
            npar = point["n_params"]
            rss = (point["rmse"] ** 2) * n
        aic = n * math.log(rss / n) + 2 * npar
        summary.append((kind, npar, math.sqrt(rss / n), aic, got))
        extra = ""
        # The isolated fit keys `point` by ARM, so point.get("E") is None
        # there and every "is this shared?" test below would wrongly say yes.
        joint = kind != "isolated"
        if joint and not point.get("E_fixed"):
            lo, hi = ci.get("E", (float("nan"),) * 2)
            extra += (f" The shared $E$ is ${point['E']:.4f}$ "
                      rf"$[{lo:.4f},\,{hi:.4f}]$.")
        if joint and not isinstance(point.get("beta"), dict):
            lo, hi = ci.get("beta", (float("nan"),) * 2)
            extra += (rf" $\beta$ is shared at ${point['beta']:.4f}$ "
                      rf"$[{lo:.4f},\,{hi:.4f}]$.")
        cap = caption + extra + (
            f" RMSE is per arm, over that arm's cells only. Bootstrap "
            f"intervals are the 2.5th--97.5th percentiles of {got} "
            f"replicates, resampled within each arm.")
        # THE FORM GOES IN THE NAME, or --form chinchilla silently overwrites
        # the Skaling tables with a different functional form under the same
        # filename and the same \label. Skaling keeps the bare name so that
        # existing \input lines keep working.
        suffix = "" if a.form == "skaling" else f"_{a.form}"
        txt = table(kind, point, ci, got, n, arms, a.form, cap,
                    label + suffix.replace("_", "-"))
        path = a.out / f"scaling_fit_{kind}{suffix}.tex"
        path.write_text(txt)
        print(f"    -> {path}", flush=True)

    print(f"\n{'fit':<10s} {'params':>7s} {'rmse':>9s} {'AIC':>10s} {'reps':>5s}")
    for kind, npar, rmse, aic, got in summary:
        print(f"{kind:<10s} {npar:>7d} {rmse:>9.5f} {aic:>10.1f} {got:>5d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
